sudo: required

language: generic

services:
  - docker

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.local

env:
- TAG=0.1

before_install:
- docker build --file Dockerfile-${TAG} -t phlummox/carnap-build-B:${TAG} .

run:


- docker ps -a
- docker images -a

script:
- docker --version
- docker run --rm phlummox/carnap-build-B stack --version
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push phlummox/carnap-build-B:${TAG}

