sudo: required

language: generic

services:
  - docker

cache:
  directories:
  - $HOME/.local

env:
- |
  IMAGE=carnap-docker-b
  TAG=0.4


before_install:
- set -x; docker build --file Dockerfile-${TAG} -t phlummox/${IMAGE}:${TAG} .

run:
- docker ps -a
- docker images -a

script:
- docker --version
- docker run --rm phlummox/${IMAGE}:${TAG} stack --version
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push phlummox/${IMAGE}:${TAG}

