
FROM phlummox/carnap-docker-b:0.1

ENV GHCJS_YAML=stack-ghcjs.yaml

COPY ${GHCJS_YAML} /tmp

RUN \
  mkdir /opt/ghcjs && \
  cd /opt/ghcjs && \
  cp /tmp/${GHCJS_YAML} . && \
  stack --stack-yaml=${GHCJS_YAML} --allow-different-user setup
